export enum TicketStatus {
  NEW = "NEW",
  OPEN = "OPEN",
  IN_PROGRESS = "IN_PROGRESS",
  WAITING_CUSTOMER = "WAITING_CUSTOMER",
  WAITING_THIRD_PARTY = "WAITING_THIRD_PARTY",
  ON_HOLD = "ON_HOLD",
  RESOLVED = "RESOLVED",
  CLOSED = "CLOSED",
}